const {
  StacksTestnet,
  TransactionVersion
} = require('@blockstack/stacks-transactions');


const API_URL = "https://stacks-node-api.blockstack.org";

const STX_MULTIPLIER = 1000000;

const POX_ERRORS = {
  1: "ERR_STACKING_INSUFFICIENT_FUNDS",
  2: "ERR_STACKING_INVALID_LOCK_PERIOD",
  3: "ERR_STACKING_ALREADY_STACKED",
  4: "ERR_STACKING_NO_SUCH_PRINCIPAL",
  5: "ERR_STACKING_EXPIRED",
  6: "ERR_STACKING_STX_LOCKED",
  9: "ERR_STACKING_PERMISSION_DENIED",
  11: "ERR_STACKING_THRESHOLD_NOT_MET",
  12: "ERR_STACKING_POX_ADDRESS_IN_USE",
  13: "ERR_STACKING_INVALID_POX_ADDRESS",
  17: "ERR_STACKING_ALREADY_REJECTED",
  18: "ERR_STACKING_INVALID_AMOUNT",
  19: "ERR_NOT_ALLOWED",
  20: "ERR_STACKING_ALREADY_DELEGATED",
  21: "ERR_DELEGATION_EXPIRES_DURING_LOCK",
  22: "ERR_DELEGATION_TOO_MUCH_LOCKED",
  23: "ERR_DELEGATION_POX_ADDR_REQUIRED",
  24: "ERR_INVALID_START_BURN_HEIGHT",
  255: "ERR_STACKING_UNREACHABLE"
}

module.exports = {
  API_URL,
  STX_MULTIPLIER,
  POX_ERRORS,
  NETWORK_STR: 'testnet',
  NETWORK: new StacksTestnet(),
  TRANSACTION_VERSION: TransactionVersion.Testnet
}
